### ISSUE TITLE
Missing dep: yaml-front-matter

### ISSUE THREAD

**Issue by h404bi** [LouisBarranqueiro/tranquilpeak-hexo-theme#106]
`dev` version. You add [scripts/filters/front-matter-excerpt.js](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/commit/26cc2483ebca5056c1cf383dfb0ed493d703d485#diff-4dcdb9b63538e7997e7891e49cd7389bR1), it requires `yaml-front-matter`, which isn't included into package.json. And after generating files, run `hexo s` will output error.

``` sh
$hexo s
ERROR Script load failed: themes\tranquilpeak\scripts\filters\front-matter-excerpt.js
Error: Cannot find module 'yaml-front-matter'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\hanabi\test\t2\node_modules\hexo\lib\hexo\index.js:213:21)
    at C:\Users\hanabi\test\t2\themes\tranquilpeak\scripts\filters\front-matter-excerpt.js:1:76
    at C:\Users\hanabi\test\t2\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\hanabi\test\t2\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
INFO  Hexo is running at http://0.0.0.0:4000/. Press Ctrl+C to stop.
```

Add `yaml-front-matter` dep would fix. :coffee:

**Comment by Imyssed** [comment]
╮(╯▽╰)╭just run `npm i yaml-front-matter` in hexo folder.

**Comment by LouisBarranqueiro** [comment]
yeah, you are right, I will add it to the package.json. Thanks you :)
